import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class SettingsStaticTests(unittest.TestCase):
    def test_recording_filename_format_control_is_wired(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("filenameFormatSelect", html)
        self.assertIn("username_timestamp", html)
        self.assertIn("Recording Filename Format", html)
        self.assertIn("filenameFormatSelect", js)
        self.assertIn("data.filename_format || 'timestamp'", js)
        self.assertIn("updateRecordingSetting('filename_format', this.value)", html)

    def test_auto_record_uses_configured_interval_and_cooldown(self):
        main = (ROOT / "app" / "main.py").read_text()

        self.assertNotIn("await asyncio.sleep(180)", main)
        self.assertIn("check_interval = await get_check_interval_seconds(db)", main)
        self.assertIn("failure_cooldowns", main)

    def test_settings_header_status_badge_is_removed(self):
        html = (ROOT / "static" / "settings.html").read_text()

        self.assertNotIn("settings-page-kicker", html)
        self.assertNotIn("Settings status", html)
        self.assertNotIn("settingsApiPill", html)
        self.assertNotIn("settingsApiDot", html)

    def test_shared_header_does_not_show_gitops_button(self):
        header = (ROOT / "static" / "header.html").read_text()
        loader = (ROOT / "static" / "loader.js").read_text()

        self.assertNotIn("GitOps", header)
        self.assertNotIn("gitStatusBtn", header)
        self.assertNotIn("gitStatusIcon", header)
        self.assertNotIn("gitStatusText", header)
        self.assertNotIn("/api/git/status", loader)
        self.assertNotIn("checkGitStatus", loader)
        self.assertIn('id="logoutBtn"', header)

        # Settings sits left of Log out; Media/Discover sit beside the logo.
        self.assertLess(header.find('href="/settings"'), header.find('id="logoutBtn"'))
        self.assertLess(header.find('class="logo"'), header.find('data-page="media"'))
        self.assertIn('header-left', header)
        self.assertIn("data.authentication_required", loader)
        self.assertIn("fetch('/api/logout', { method: 'POST' })", loader)

    def test_settings_application_tab_is_removed(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertNotIn('data-tab="application"', html)
        self.assertNotIn('id="tab-application"', html)
        self.assertNotIn('id="appVersionSetting"', html)
        self.assertNotIn('id="apiStatus"', html)
        self.assertNotIn("appVersionSetting", js)

    def test_flaresolverr_settings_url_can_be_edited(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("flareUrlInput", html)
        self.assertIn("flareSaveBtn", html)
        self.assertIn("saveFlareSolverrUrl", js)
        self.assertIn("loadFlareSolverrSettings", js)
        self.assertIn("/api/settings/flaresolverr", js)
        self.assertIn("FlareSolverr URL saved", js)
        self.assertNotIn("configured via environment variables", html)

    def test_flaresolverr_is_not_configured_by_environment_variables(self):
        files = [
            "app/main.py",
            "app/core/config.py",
            "app/providers/browser.py",
            "app/services/flaresolverr.py",
            "docker-compose.yml",
            "README.md",
        ]
        text = "\n".join((ROOT / path).read_text() for path in files)

        self.assertNotIn("FLARESOLVERR_URL", text)
        self.assertNotIn("HXYLIVE_FLARESOLVERR_URL", text)
        self.assertNotIn("FLARESOLVERR_MAX_TIMEOUT", text)
        self.assertNotIn("HXYLIVE_FLARESOLVERR_TIMEOUT_MS", text)
        self.assertNotRegex(text, r"os\.getenv\([^)]*FLARESOLVERR")

    def test_recording_settings_exposes_check_interval_control(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn('id="checkIntervalInput"', html)
        self.assertIn("check_interval_seconds", html)
        self.assertIn("function normalizeCheckIntervalSeconds", js)
        self.assertIn("function setCheckIntervalInput", js)
        self.assertIn("data.check_interval_seconds", js)

    def test_recording_settings_exposes_gap_buffer_not_auto_sync(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn('id="gapBufferMinutesSelect"', html)
        self.assertIn("gap_buffer_minutes", html)
        self.assertIn("download_project_concurrency", html)
        self.assertIn("download_file_concurrency", html)
        self.assertIn("gapBufferMinutesSelect", js)
        self.assertNotIn('id="macAutoSyncToggle"', html)
        self.assertNotIn('id="macAutoSyncMethodSelect"', html)
        self.assertIn('id="recordingEnabledToggle"', html)
        self.assertIn("recording_enabled", html)
        self.assertIn("data.recording_enabled !== false", js)
        self.assertIn('id="defaultMonthlyQuotaInput"', html)
        self.assertIn("default_monthly_quota_gb", html)
        self.assertIn('id="quotaCycleDayInput"', html)
        self.assertIn("quota_cycle_day", html)
        self.assertIn("function normalizeMonthlyQuotaGb", js)
        self.assertIn("function normalizeQuotaCycleDay", js)
        self.assertIn("hxylive:recording-enabled", js)
        header = (ROOT / "static" / "header.html").read_text()
        self.assertNotIn("headerMacAutoSyncBtn", header)
        self.assertNotIn("headerRecordingEnabledBtn", header)
        self.assertIn("headerMediaLogBtn", header)
        self.assertIn("header-center", header)
        self.assertLess(header.find("header-center"), header.find("header-right"))
        loader = (ROOT / "static" / "loader.js").read_text()
        self.assertIn("bindHeaderMediaLog", loader)
        self.assertNotIn("bindHeaderRecordingControls", loader)
        self.assertNotIn("headerMacAutoSyncBtn", loader)
        self.assertNotIn("headerRecordingEnabledBtn", loader)
        self.assertIn("header.html?v=hxylive-ui10", loader)
        # Media activity log: reveal only on /media; CSS must respect [hidden].
        self.assertIn("pathname.indexOf('/media') === 0", loader)
        css = (ROOT / "static" / "styles.css").read_text()
        self.assertIn(".header-media-log:not([hidden])", css)
        self.assertIn(".header-media-log[hidden]", css)
        self.assertIn(".header-center", css)

    def test_blacklisted_tags_use_dom_events_instead_of_inline_javascript(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("removeButton.addEventListener('click'", js)
        self.assertIn("chip.appendChild(document.createTextNode(String(tag)))", js)
        self.assertNotIn("onclick=\"removeBlacklistedTag", js)

    def test_dynamic_inline_handlers_use_javascript_string_escaping(self):
        for filename in ("discover.js", "settings.js"):
            js = (ROOT / "static" / filename).read_text()
            self.assertIn("function escapeInlineJs(value)", js, filename)
            self.assertIn(".replace(/'/g, '\\\\x27')", js, filename)
            self.assertIn(".replace(/</g, '\\\\x3c')", js, filename)

        discover = (ROOT / "static" / "discover.js").read_text()
        settings = (ROOT / "static" / "settings.js").read_text()
        self.assertIn("openCreateCardDialog(\\'' + escapeInlineJs(model.username)", discover)
        self.assertIn("navigator.clipboard.writeText(\\'' + escapeInlineJs(input)", settings)

    def test_hls_player_dependency_is_version_pinned_with_integrity(self):
        expected_src = "https://cdn.jsdelivr.net/npm/hls.js@1.6.16/dist/hls.min.js"
        expected_integrity = (
            "sha384-5E8B0pTlZZJMabWpC0fyYf6OUpe15jJij34BqBAh4NXoHAlLNOjCPRrwtOXOQFAn"
        )
        html = (ROOT / "static" / "watch.html").read_text()
        self.assertIn(expected_src, html)
        self.assertIn(expected_integrity, html)
        self.assertIn('crossorigin="anonymous"', html)
        self.assertNotIn("hls.js@latest", html)

    def test_watch_quality_switches_server_renditions_for_single_level_hls(self):
        html = (ROOT / "static" / "watch.html").read_text()
        js = (ROOT / "static" / "watch.js").read_text()
        main = (ROOT / "app" / "main.py").read_text()

        self.assertIn('id="watchQualitySelect"', html)
        self.assertIn("serverQualityOptions = [1080, 720, 480]", js)
        self.assertIn("function watchQualityHeights()", js)
        self.assertIn("Auto (network ABR)", js)
        self.assertNotIn("return 'Source'", js)
        self.assertNotIn("return 'Source '", js)
        self.assertNotIn(">Source</option>", js)
        self.assertNotIn("Source ' + ordinal", js)
        self.assertIn("query.quality = Number(quality)", js)
        self.assertIn("server:' + height", js)
        self.assertIn("startStreamWithUrl(data.streamUrl, data.streamType, true)", js)
        self.assertIn("quality: Optional[int] = None", main)
        self.assertIn('"qualityOptions": [1080, 720, 480]', main)
        self.assertIn("max_height = quality", main)

    def test_watch_pause_does_not_auto_resume_on_hls_level_reload(self):
        js = (ROOT / "static" / "watch.js").read_text()
        self.assertIn("let userPausedLive = false", js)
        self.assertIn("function pauseLivePlayback()", js)
        self.assertIn("if (!video || userPausedLive) return", js)
        self.assertNotIn("if (video.paused) startMutedAutoplay(video)", js)

    def test_tests_center_covers_local_diagnostics(self):
        js = (ROOT / "static" / "settings.js").read_text()
        test_ids = set(re.findall(r"id: '([^']+)'", js))

        self.assertTrue(
            {
                "api",
                "routes",
                "providers",
                "system",
                "recording",
                "following",
                "processes",
                "flaresolverr",
                "recordings",
                "media-imports",
                "blacklist",
            }.issubset(test_ids)
        )
        self.assertNotIn("chaturbate", test_ids)
        self.assertNotIn("cam4", test_ids)
        self.assertNotRegex(js, r"id:\s*'chaturbate'")
        self.assertNotRegex(js, r"id:\s*'cam4'")
        self.assertNotRegex(js, r"name:\s*'Chaturbate account'")
        self.assertNotRegex(js, r"name:\s*'CAM4 account'")
        self.assertIn("Legacy dashboard route still exists", js)
        self.assertIn("Removed provider still registered", js)
        self.assertIn("Missing status for", js)
        self.assertIn("All five providers should expose account login", js)
        self.assertIn("All five providers should expose remote sync", js)

    def test_following_page_lists_local_follow_providers(self):
        header = (ROOT / "static" / "header.html").read_text()
        main = (ROOT / "app" / "main.py").read_text()
        self.assertFalse((ROOT / "static" / "following.js").exists())
        self.assertNotIn('href="/following"', header)
        self.assertIn('RedirectResponse(url="/media"', main)

    def test_media_page_has_profile_filter_and_continuous_playback(self):
        html = (ROOT / "static" / "media.html").read_text()
        header = (ROOT / "static" / "header.html").read_text()
        js = (ROOT / "static" / "media.js").read_text()
        css = (ROOT / "static" / "styles.css").read_text()

        self.assertNotIn('href="/recordings"', header)
        self.assertNotIn('data-page="recordings"', header)
        self.assertNotIn("Recordings</a>", header)
        self.assertIn('href="/media" class="nav-link" data-page="media">Media</a>', header)
        self.assertNotIn('href="/stash"', header)
        self.assertIn("<title>Media - HXYLIVE</title>", html)
        self.assertNotIn("mediaNewProfileBtn", html)
        self.assertNotIn("mediaProfileFilter", html)
        self.assertNotIn("mediaAutoRecordFilter", html)
        self.assertNotIn("mediaProfilePrev", html)
        self.assertNotIn("mediaProfileNext", html)
        self.assertNotIn("mediaProfileDetail", html)
        self.assertNotIn("mediaProfileFilterBtn", html)
        self.assertNotIn("mediaProfileClearBtn", html)
        self.assertNotIn("mediaUploadBtn", html)
        self.assertNotIn("mediaUploadForm", html)
        self.assertNotIn("/uploads", html)
        self.assertNotIn("Date of birth", html)
        self.assertNotIn("Babepedia page URL", html)
        self.assertNotIn("Fetch Babepedia image", html)
        self.assertIn("Identity", html)
        self.assertIn("Recording sources", html)
        self.assertIn("Display name", html)
        self.assertIn("profileSourcesList", html)
        self.assertIn("profileAddSourceBtn", html)
        self.assertIn("Add source", html)
        self.assertNotIn("mediaUnwatchedOnlyToggle", html)
        self.assertNotIn(">Unwatched<", html)
        self.assertIn("profileImageUrl", js)
        self.assertIn("streamSources", js)
        self.assertIn("channelUsername", js)
        self.assertIn("channelUsernameFromUrl", js)
        self.assertIn("sourceTypeFromUrl", js)
        self.assertIn("{ value: 'twitch', label: 'Twitch'", js)
        self.assertIn("{ value: 'youtube', label: 'YouTube'", js)
        self.assertIn("{ value: 'chaturbate', label: 'Chaturbate'", js)
        self.assertIn("selectedProfile", js)
        self.assertIn("filterProfile", js)
        self.assertIn("formatProfileMediaCounts", js)
        self.assertNotIn("mediaProfileFilter", js)
        self.assertNotIn("autoRecordFilter", js)
        self.assertIn("profileSearch", js)
        self.assertIn("function visibleProfiles()", js)
        self.assertIn("profileSortRank", js)
        self.assertIn("media-settings-toggle", js)
        self.assertIn(".media-reconcile-section", css)
        self.assertIn(".media-profile-card.is-recording", css)
        self.assertIn("No streamers match this filter", js)
        self.assertNotIn("media-profile-menu-btn", js)
        self.assertNotIn("Cmd/Ctrl-click or long-press for streamer settings", js)
        self.assertIn('data-profile-action="watch"', js)
        self.assertNotIn("media-profile-edit-btn", js)
        self.assertNotIn('data-profile-action="edit"', js)
        self.assertIn("mediaStreamerSettingsBtn", html)
        self.assertIn("openStreamerSettingsFromToolbar", js)
        self.assertIn("openStreamerSettingsPicker", js)
        self.assertIn("openProfileSettings(username)", js)
        self.assertNotIn("renderProfileDetail", js)
        self.assertNotIn("filterSelectedProfile", js)
        self.assertNotIn("clearSelectedProfile", js)
        self.assertIn("showNextPrompt", js)
        self.assertIn("nextVideoItem", js)
        self.assertIn("data-next-action", js)
        self.assertIn("setupMediaProfileVolume", js)
        self.assertIn("video_volume_' + username", js)
        self.assertIn("/api/models/' + encodeURIComponent(username) + '/volume", js)
        self.assertIn("window.addEventListener('beforeunload', flushMediaProfileVolume)", js)
        self.assertNotIn("openUploadModal", js)
        self.assertNotIn("uploadMediaFiles", js)
        self.assertNotIn("/uploads", js)
        self.assertNotIn("<label>Channel<input", js)
        self.assertNotIn('data-source-field="channelUsername" type="text"', js)
        self.assertNotIn("profile.thumbnail", js)
        self.assertNotIn("unwatchedOnly", js)
        self.assertNotIn("params.set('watched', 'unwatched')", js)
        self.assertNotIn('media-tag watched', js)
        self.assertIn("params.set('metadata', 'lazy')", js)
        self.assertIn("formatDurationClock", js)
        self.assertIn("value.getFullYear()", js)
        self.assertIn("item.resolution", js)
        self.assertIn("formatVideoStreamMeta", js)
        self.assertIn("formatFps", js)
        self.assertIn("formatBitrate", js)
        self.assertIn("matching videos", js)
        self.assertIn("media-heading-count", js)
        self.assertNotIn("All devices", js)
        self.assertNotIn("media-heading-filters", js)
        self.assertIn("mediaSelectAllBtn", html)
        self.assertIn("mediaStreamerBatchActions", html)
        self.assertIn("mediaFollowSyncBtn", html)
        self.assertIn("mediaStreamerFilterResetBtn", html)
        self.assertIn("startMediaFollowSync", js)
        self.assertIn("openFollowReconcile", js)
        self.assertIn("/following/reconcile", js)
        self.assertIn("/api/media-profiles/ensure-card", js)
        self.assertIn("mediaFollowSyncModal", html)
        self.assertNotIn("mediaFollowSyncRescan", html)
        header = (ROOT / "static" / "header.html").read_text()
        self.assertIn("headerMediaLogBtn", header)
        self.assertIn("headerMediaLogText", header)
        self.assertNotIn("mediaFollowSyncLogBtn", html)
        self.assertIn("mediaSyncLogModal", html)
        self.assertIn("appendSyncLog", js)
        self.assertIn("appendMediaLog", js)
        self.assertIn("preserveSelection", js)
        self.assertIn("media-reconcile-result", js)
        self.assertIn("mediaFollowSyncResult", html)
        self.assertIn("media-ps-dialog", html)
        self.assertIn("media-settings-toggle-state", js)
        self.assertIn("importProviderSessionFromChromeForSync", js)
        self.assertNotIn("Unfollow and delete cards", js)
        self.assertNotIn("Cmd/Ctrl-click or long-press to choose", js)
        self.assertNotIn("mediaFollowSyncSelectLocal", html)
        self.assertNotIn("mediaFollowSyncConfirm", html)
        self.assertNotIn("mediaStreamerFollowBtn", html)
        self.assertNotIn("mediaStreamerUnfollowBtn", html)
        self.assertIn("mediaStreamerStartRecordBtn", html)
        self.assertIn("mediaStreamerStopRecordBtn", html)
        self.assertIn("mediaStreamerDeleteBtn", html)
        self.assertNotIn("bulkFollowSelectedStreamers", js)
        self.assertNotIn("bulkUnfollowSelectedStreamers", js)
        self.assertIn("bulkStartRecordingSelectedStreamers", js)
        self.assertIn("confirmStreamerBulkDelete", js)
        self.assertIn("is-unfollowed", js)
        self.assertNotIn("media-profile-rec-badge", js)
        self.assertIn("/api/media-profiles/bulk/delete", js)
        self.assertNotIn("mediaInvertSelectionBtn", html)
        self.assertIn("mediaSelectPageBtn", html)
        self.assertIn("mediaClearSelectionBtn", html)
        self.assertIn("selectAllVisibleVideos", js)
        self.assertIn("selectAllPageVideos", js)
        self.assertIn("clearVideoSelection", js)
        self.assertNotIn("invertVisibleVideoSelection", js)
        self.assertIn("mediaDateRange", html)
        self.assertIn("applyDateRangeFilter", js)
        self.assertIn("shiftMediaPage", js)
        self.assertIn("mediaVideoPrevPageBtn", html)
        self.assertIn("mediaVideoNextPageBtn", html)
        self.assertNotIn("mediaFollowSyncStatus", html)
        self.assertNotIn("mediaVideoSearchInput", html)
        self.assertIn("hxylive:header-ready", js)
        self.assertIn('class="media-card-profile-id"', js)
        self.assertIn('data-media-action="profile"', js)
        self.assertIn("profileIdLabel", js)
        self.assertIn("profileStatusClass", js)
        self.assertNotIn("Cmd/Ctrl-click or long-press for streamer settings", js)
        self.assertIn("media-profile-name-text", js)
        self.assertIn("profileLabel(profileForItem)", js)
        self.assertIn("selectProfile(profileLink.dataset.profile || '', true)", js)
        self.assertIn('data-profile-action="watch"', js)
        self.assertIn("/api/media-profiles/' + encodeURIComponent(username) + '/auto-record", js)
        self.assertIn("recordingPayloadFromProfile", js)
        self.assertIn("items: items, autoRecord: true", js)
        self.assertIn("Recording enabled for ", js)
        self.assertIn("media-profile-live-link", js)
        self.assertNotIn("preferOnline", js)
        self.assertNotIn("ev.metaKey || ev.ctrlKey", js)
        self.assertNotIn("Online playback needs a VPS copy of this video", js)
        self.assertNotIn("⌘/Ctrl-click for online viewer", js)
        self.assertNotIn("&#9679;", js)
        self.assertNotIn("&#9675;", js)
        self.assertNotIn("media-profile-follow-btn", js)
        self.assertNotIn("media-profile-record-btn", js)
        self.assertNotIn("media-profile-watch-btn", js)
        self.assertNotIn("media-profile-select-wrap", js)
        self.assertNotIn("media-streamer-status", js)
        self.assertNotIn("profileSettingsPressTimer", js)
        self.assertIn("openProfileSettings(username)", js)
        self.assertIn("openStreamerSettingsFromToolbar", js)
        self.assertIn("profile.autoRecord = !!data.autoRecord", js)
        self.assertIn("profile.streamSources = data.profile.streamSources", js)
        self.assertNotIn("Object.assign(profile, data.profile)", js)
        self.assertIn("mediaStorage", html)
        self.assertIn("mediaStorageRefreshBtn", html)
        self.assertIn("mediaProfileRefreshBtn", html)
        self.assertIn("VPS storage", html)
        self.assertNotIn("VPS storage health", html)
        self.assertNotIn("mediaStorageHealth", html)
        self.assertNotIn("Storage looks healthy", html)
        self.assertNotIn("Recording folder", html)
        self.assertIn("Processing / temporary", html)
        self.assertIn("mediaProcessingBrowseBtn", html)
        self.assertIn("mediaProcessingModal", html)
        self.assertIn("media-processing-col-modified", html)
        self.assertIn("formatDateTimeSeconds(file.modifiedAt)", js)
        self.assertIn("processing-files", js)
        self.assertIn("openProcessingModal", js)
        self.assertIn("deleteSelectedProcessingFiles", js)
        self.assertNotIn("mediaDiskUsedPercent", html)
        self.assertNotIn("mediaDiskFreePercent", html)
        self.assertNotIn("mediaDiskSummary", html)
        self.assertNotIn("mediaDiskLegend", html)
        self.assertIn("media-storage-segment-label", js)
        self.assertIn("Usable disk breakdown", html)
        self.assertIn("diskFreePercent", js)
        self.assertIn("diskUsableBytes", js)
        self.assertNotIn("% full", js)
        self.assertNotIn('id="mediaVideoCount"', html)
        self.assertNotIn('id="mediaTotalSize"', html)
        self.assertNotIn("Videos:", html)
        self.assertNotIn('class="media-stats"', html)
        self.assertIn("media.js?v=hxylive-proj2", html)
        self.assertIn("styles.css?v=hxylive-ui52", html)
        self.assertIn("mediaTasksModal", html)
        self.assertIn("profileGapBufferMinutes", html)
        self.assertIn("openTasksModal", js)
        self.assertIn("gap_buffer_minutes", js)
        self.assertIn("Mac file(s) and", js)
        self.assertIn("rewriteChaturbatePosterUrl", js)
        self.assertIn("ensureProfilesForLocalVideos", js)
        self.assertIn("fillMissingChaturbateAvatars", js)
        self.assertIn("pageProfiles", js)
        self.assertIn("selectAllFilteredStreamers", js)
        self.assertIn("resolveLocalIdentityToProfileUsername", js)
        self.assertIn("Select all", html)
        self.assertIn("Select page", html)
        self.assertIn("mediaStreamerSelectPageBtn", html)
        self.assertNotIn("media-profile-website-actions", html)
        self.assertNotIn("media-follow-sync-check", js)
        self.assertNotIn("media-profile-id", js)
        self.assertIn("fromMacLocal", js)
        self.assertIn("makeLocalVideoProfile", js)
        self.assertIn("hydrateLocalVideoProfileAvatars", js)
        self.assertIn("fetchLocalVideoLiveMeta", js)
        self.assertIn("'/api/model/' + encodeURIComponent(profile.username) + '/status'", js)
        self.assertIn("/api/discover/profile-images", js)
        self.assertIn("localProfileLiveMeta", js)
        self.assertIn("isRecordingThumbAvatarUrl", js)
        self.assertIn("parseIdentityWithSource", js)
        self.assertIn("channelUrlForSource", js)
        self.assertIn("loader.js?v=hxylive-confirm9", html)
        self.assertIn("hxyliveConfirm", (ROOT / "static" / "loader.js").read_text())
        self.assertIn(".hxylive-confirm-modal", css)
        self.assertIn("media-profile-last-live-row", js)
        self.assertIn("openDownloadMethodModal", js)
        self.assertIn("closeDownloadMethodModal", js)
        self.assertIn("normalizeDownloadMethod", js)
        self.assertIn("mediaDownloadMethodModal", html)
        self.assertIn("mediaDownloadWithMotrix", html)
        self.assertIn("mediaDownloadWithChrome", html)
        self.assertIn("method: downloadMethod", js)
        self.assertIn(".media-download-method-btn", css)
        self.assertIn("formatLastLive", js)
        self.assertIn("media-profile-last-live", js)
        self.assertIn("lastLiveAt", js)
        self.assertIn("file.resolution", js)
        self.assertIn("styles.css?v=hxylive-ui52", html)
        self.assertIn(".media-follow-sync-card.is-selected", css)
        self.assertIn("data-reconcile-open-channel", js)
        self.assertIn("reconcileChannelUrl", js)
        self.assertIn("selectedCount", js)
        self.assertIn("action.label + ' (' + selectedCount + ')'", js)
        self.assertIn("updateReconcileSectionActionLabels", js)
        self.assertIn("scrollByBucket", js)
        self.assertIn("background: transparent !important", css)
        self.assertIn("applyMediaVideoBoxSize", js)
        self.assertIn("parseMediaResolution", js)
        self.assertIn("object-position: center center", css)
        self.assertIn("{ value: 'locked', label: 'Locked' }", js)
        self.assertIn("function profileStatusDetail", js)
        self.assertIn(".media-profile-live-meta .locked", css)
        self.assertIn(".media-batch-actions .media-action-btn", (ROOT / "static" / "styles.css").read_text())
        self.assertIn("media-card-title-row", js)
        self.assertIn(".media-card-title-row", css)
        self.assertIn("showQuality", js)
        self.assertIn("refreshProfiles", js)
        self.assertIn("live_refresh", js)
        self.assertIn("scanMacAndRefresh(true, true)", js)
        self.assertIn("media-refresh-btn", html)
        self.assertIn(".media-refresh-btn", css)
        self.assertIn("mediaDeviceFilters", html)
        self.assertNotIn('data-device="all"', html)
        self.assertIn('data-device="vps"', html)
        self.assertIn('data-device="mac"', html)
        self.assertNotIn('data-device="both"', html)
        self.assertIn('class="media-device-btn active" data-device="vps"', html)
        self.assertIn('class="media-device-btn active" data-device="mac"', html)
        self.assertIn("deviceFilters: ['vps', 'mac']", js)
        self.assertIn("resetVideoFilters", js)
        self.assertIn("setSortField", js)
        self.assertIn("sortField: 'name'", js)
        self.assertIn("sortDir: 'desc'", js)
        self.assertIn("media-video-toolbar", html)
        self.assertIn(".media-video-toolbar", css)
        self.assertIn("mediaVideoFilterResetBtn", html)
        self.assertIn("media-toolbar-search-row", html)
        self.assertIn('data-sort-field="name"', html)
        self.assertIn('data-sort-field="size"', html)
        self.assertNotIn('data-sort="newest"', html)
        self.assertNotIn('data-sort="oldest"', html)
        self.assertIn("profileLabel(profileByUsername(selected[0]))", js)
        self.assertIn("media-heading-profile", html)
        self.assertIn('id="mediaProfileMeta"', html)
        self.assertNotIn("itemIsBoth", js)
        self.assertIn("media-toolbar-sep", html)
        self.assertIn(".media-toolbar-sep", css)
        self.assertIn("color: #a5b4fc !important", css)
        self.assertNotIn("mediaUnsyncedOnlyToggle", html)
        self.assertIn("buildUnifiedCatalog", js)
        self.assertIn("setDeviceFilter", js)
        self.assertIn("openLocally", js)
        self.assertIn("itemIsSelectable", js)
        self.assertIn("deleteSelectedMacCopies", js)
        self.assertIn("classifyDeleteItems", js)
        self.assertIn("buildDeletePlan", js)
        self.assertNotIn("mediaDeleteBothBody", html)
        self.assertNotIn("pendingBothChoices", js)
        self.assertNotIn("mediaDeleteBothPanel", html)
        self.assertIn("purgedVps", js)
        self.assertIn("macThumbUrl", js)
        self.assertIn("locationLabel", js)
        self.assertIn("displayMediaTitle", js)
        self.assertIn("displayMediaIdTitle", js)
        self.assertIn("formatDateTimeSeconds", js)
        self.assertIn(":not(.media-refresh-btn)", css)
        self.assertIn(".media-refresh-btn", css)
        self.assertIn("background: var(--accent) !important", css)
        self.assertIn("reveal-local", js)
        self.assertIn("helperPostOrQueue('/open'", js)
        self.assertIn("helperPostOrQueue('/delete'", js)
        self.assertIn("/api/mac/helper/open", js)
        self.assertIn("/api/mac/helper/delete", js)
        self.assertIn("helperPostOrQueue", js)
        self.assertIn("MAC_HELPER_BASE + '/thumb?'", js)
        self.assertIn("/api/mac/helper/thumb?", js)
        self.assertIn("retryMacThumb", js)
        self.assertIn("watchFiledDownloads", js)
        self.assertIn("refreshMacListAfterFile", js)
        self.assertIn("MAC_HELPER_BASE + '/wait-filed'", js)
        self.assertIn("fetchVpsMacSnapshot", js)
        self.assertIn("applyMacSnapshot", js)
        self.assertIn("/api/mac/helper/snapshot", js)
        self.assertIn("macHelperDirect", js)
        self.assertIn(".media-device-filters", css)
        self.assertIn(".media-card-footer", css)
        self.assertIn(".media-card-open-folder", css)
        self.assertIn("Open folder", js)
        self.assertIn("media-card-footer-btn", js)
        self.assertNotIn("Recorded: ", js)
        self.assertIn("background: transparent !important", css)
        self.assertNotIn("mediaDeleteMacOnly", html)
        self.assertNotIn("mediaDeleteVpsOnly", html)
        self.assertNotIn("Delete Mac only", html)
        self.assertNotIn("Delete VPS only", html)
        self.assertNotIn(".media-delete-both-table", css)
        self.assertNotIn(".loc-both", css)
        self.assertIn(".media-loc-tag", css)
        self.assertIn("media-filter-zone-buttons", html)
        self.assertIn(".media-filter-zone-buttons", css)
        self.assertIn("media-streamer-toolbar", html)
        self.assertIn("media-profile-channel-line", js)
        self.assertIn("providerLabel(sourceType)", js)
        self.assertIn("isLiveCoverAvatarUrl", js)
        self.assertIn("thumb\\.live\\.mmcdn\\.com\\/riw\\/", js)
        self.assertIn("previews-ttv", js)
        self.assertIn("live_user_", js)
        self.assertIn('referrerpolicy="no-referrer"', js)
        self.assertIn(".media-profile-channel-line", css)
        self.assertIn("data.storage", js)
        self.assertIn("recordingFolderBytes", js)
        self.assertIn("diskUsableBytes", js)
        self.assertIn("diskFreeFormatted", js)
        self.assertIn("mediaStorageRefreshBtn", js)
        self.assertIn("mediaProfileRefreshBtn", js)
        self.assertIn('id="mediaProfileRefreshBtn"', html)
        self.assertIn('id="mediaStorageRefreshBtn"', html)
        self.assertIn('id="mediaProfileRefreshBtn"', html)
        self.assertIn('class="media-profile-source-btn media-refresh-btn" id="mediaStorageRefreshBtn"', html)
        self.assertNotIn("$('mediaVideoCount')", js)
        self.assertNotIn("$('mediaTotalSize')", js)
        self.assertIn(".media-storage-section", css)
        self.assertIn(".media-storage-bar", css)
        self.assertNotIn(".media-storage-refresh-btn", css)
        self.assertNotIn("Every recording in this filter", js)
        self.assertNotIn("media-open-local-btn", js)
        self.assertNotIn(">Open locally<", js)
        self.assertNotIn("return 'BOTH'", js)
        self.assertIn("return 'MAC'", js)
        self.assertIn("return 'VPS'", js)
        self.assertIn(".media-storage-segment-label", css)
        self.assertIn(".media-storage-free-pct", css)
        self.assertIn(".media-storage-segment-system", css)
        self.assertIn(".media-storage-segment-free", css)
        self.assertIn("Temp files", html)
        self.assertIn("renderDiskBreakdown", js)
        self.assertIn("visibleMediaFormatted", js)
        self.assertIn("grid-template-columns: 1fr;", css)
        self.assertNotIn(".media-profile-rec-badge", css)
        self.assertIn(".media-reconcile-result", css)
        self.assertIn(".media-ps-dialog", css)
        self.assertIn(".media-settings-toggle-indicator", css)
        self.assertIn("var(--accent)", css)
        self.assertNotIn("media-profile-handle", js)
        self.assertNotIn("var showHandle =", js)
        self.assertIn("bulkStartRecordingSelectedStreamers", js)
        self.assertNotIn("bulkFollowSelectedStreamers", js)
        self.assertNotIn("toggleProfileFollow", js)
        self.assertNotIn("discover-follow-heart", js)
        self.assertNotIn("media-profile-follow-btn", js)
        self.assertIn(".media-profile-name.is-followed", css)
        self.assertIn("formatLastLive", js)
        self.assertIn("formatLastSeen", js)
        self.assertIn("media-profile-last-live", js)
        self.assertIn("lastLiveAt", js)
        self.assertIn("lastSeenOnlineAt", js)
        self.assertIn(".media-profile-live-link", css)
        self.assertNotIn(".media-profile-menu-btn", css)
        self.assertIn("renderAllProfilesCard", js)
        self.assertIn("media-all-profiles-card", js)
        self.assertIn('data-all-profiles="1"', js)
        self.assertIn("All streamers", js)
        self.assertIn("mediaProfileSourceFilters", html)
        self.assertIn("mediaProfileStatusFilters", html)
        self.assertIn("mediaProfileRecordingFilters", html)
        self.assertIn("filterSources", js)
        self.assertIn("filterLiveStatuses", js)
        self.assertIn("filterRecordings", js)
        self.assertIn("setProfileSourceFilter", js)
        self.assertIn("setProfileLiveStatusFilter", js)
        self.assertIn("setRecordingFilter", js)
        self.assertIn("resetProfileFilters", js)
        self.assertIn("PROFILE_LIVE_STATUS_OPTIONS", js)
        self.assertNotIn("PROFILE_GLOBAL_LIVE_STATUS_OPTIONS", js)
        self.assertIn("PROFILE_RECORDING_OPTIONS", js)
        self.assertNotIn("setGlobalLiveStatusFilter", js)
        self.assertNotIn('data-source="all"', js)
        self.assertIn("'data-live-status'", js)
        self.assertNotIn("data-global-live-status=", js)
        self.assertIn("'data-recording-filter'", js)
        self.assertIn("Recording", js)
        self.assertIn("Not recording", js)
        self.assertIn("media-filter-zone-label", html)
        self.assertIn(".media-streamer-toolbar", css)
        self.assertIn(".media-filter-zone", css)
        self.assertIn(".media-profile-source-btn", css)
        self.assertIn(".media-profile-status-btn", css)
        self.assertIn("All videos", js)
        self.assertIn("mediaProfilePagination", html)
        self.assertIn("mediaProfilePageNumbers", html)
        self.assertIn("mediaStreamerPrevPageBtn", html)
        self.assertIn("mediaStreamerNextPageBtn", html)
        self.assertIn("PROFILE_PAGE_ROWS = 3", js)
        self.assertIn("profileFirstPageStreamerCount", js)
        self.assertIn("profilePageSlice", js)
        self.assertIn("setProfilePage", js)
        self.assertIn("shiftProfilePage", js)
        self.assertIn("renderProfilePagination", js)
        self.assertIn("data-profile-page", js)
        self.assertIn(".media-profile-pagination", css)
        self.assertIn("openSyncSitePicker", js)
        self.assertIn("mediaSyncSiteModal", html)
        self.assertIn("media-toolbar-btn-fill", html)
        self.assertIn('id="mediaStreamerFilterResetBtn"', html)
        self.assertIn("mediaStreamerSettingsBtn", html)
        self.assertNotIn("Prev · Q", html)
        self.assertNotIn("Next · E", html)
        self.assertIn(">Prev<", html)
        self.assertIn(">Next<", html)
        self.assertNotIn("media-toolbar-recording-row", html)
        self.assertIn('data-zone="website"', html)
        self.assertIn('data-zone="recording"', html)
        self.assertIn("toggleToolbarCompactMode", js)
        self.assertIn("media-toolbar-compact", js)
        self.assertIn("data-media-action=\"vps-label\"", js)
        self.assertIn("title=\"Select this VPS video\"", js)
        self.assertIn("toggleDownloadSelection(vpsId", js)
        self.assertIn("classList.toggle('selected'", js)
        self.assertIn("/provider/follow", js)
        self.assertIn("remoteCompleted", js)
        self.assertIn("ensureMacHelperSession", js)
        self.assertIn("queueTwitchFollowViaMacHelper", js)
        self.assertIn("/api/mac/helper/provider-follow", js)
        self.assertIn(".media-profile-card.is-recording.is-selected", css)
        self.assertIn("flex: 0 0 4.5rem", css)
        self.assertIn("rgba(99, 102, 241, 0.55)", css)
        self.assertIn("if (width <= 1400) return 4;", js)
        self.assertIn("return 5;", js)
        self.assertIn("ensurePaginationSkeleton", js)
        self.assertIn('data-profile-page="1"', html)
        self.assertIn('data-page="1"', html)
        self.assertIn("media-picker-option-title", js)
        self.assertNotIn("media-picker-option-meta", js)
        self.assertNotIn("media-profile-edit-icon", js)
        self.assertIn("color: #a5b4fc !important", css)
        self.assertIn(".media-card-profile-id", css)
        self.assertIn("mediaSortButtons", html)
        self.assertNotIn("mediaSortSelect", html)
        self.assertIn("isWatched", js)
        self.assertNotIn("mediaUnwatchedOnlyToggle", html)
        self.assertIn(".media-next-prompt", css)
        self.assertNotIn(".media-profile-menu-btn", css)
        self.assertIn(".media-profile-name.is-unfollowed", css)
        self.assertIn(".media-profile-name.is-followed", css)
        self.assertIn("border-color: var(--accent) !important;", css)
        self.assertIn("min-height: 108px;", css)
        self.assertIn("grid-template-columns: repeat(5, minmax(0, 1fr));", css)
        self.assertIn("grid-template-columns: 70px minmax(0, 1fr);", css)
        self.assertIn("@media (max-width: 1400px)", css)
        self.assertIn("@media (max-width: 1100px)", css)
        self.assertIn("@media (max-width: 980px)", css)
        self.assertIn("overflow: hidden;", css)
        self.assertIn("renderSourceFilters({});", (ROOT / "static" / "discover.js").read_text())
        self.assertIn("if (!hasCards) {", (ROOT / "static" / "discover.js").read_text())
        self.assertNotIn(".media-profile-detail", css)
        self.assertNotIn(".media-upload-modal", css)
        self.assertNotIn("M&eacute;dia", header)
        self.assertNotIn("Non vues", html)
        self.assertNotIn("Videos non vues", js)
        self.assertNotIn("Deja vu", js)

    def test_watch_page_create_card_and_separate_recording(self):
        html = (ROOT / "static" / "watch.html").read_text()
        js = (ROOT / "static" / "watch.js").read_text()

        self.assertIn('id="createCardBtn"', html)
        self.assertIn('id="recordBtn"', html)
        self.assertIn('id="recordText"', html)
        self.assertIn("Record", html)
        self.assertIn("Create card", html)
        self.assertIn("function toggleRecording", js)
        self.assertIn("function loadCardAndRecordingStatus", js)
        self.assertIn("function openWatchCreateCardDialog", js)
        self.assertIn("/api/media-profiles/ensure-card", js)
        self.assertIn("/api/media-profiles/' + encodeURIComponent(profileUsername) + '/auto-record", js)
        self.assertIn("sourceType: source", js)
        self.assertIn("channelUsername: currentUsername", js)
        self.assertNotIn('id="followBtn"', html)
        self.assertNotIn("function toggleFollow", js)
        self.assertNotIn("recordingModal", html)
        self.assertNotIn("recordingProfileSearch", html)
        self.assertNotIn("Follow &amp; enable recording", html)
        self.assertNotIn("New profile", html)
        self.assertNotIn("/api/media-profiles/link-live", js)
        self.assertNotIn("openRecordingModal", js)
        self.assertNotIn("enableWatchFollowAndRecord", js)
        self.assertNotIn("Auto-Record", html)
        self.assertNotIn("Auto-Record", js)
        self.assertNotIn("toggleAutoRecord", js)
        self.assertIn('id="watchAvatar"', html)
        self.assertIn("watch-avatar-placeholder", html)
        self.assertIn("watch.js?v=hxylive3", html)
        self.assertIn("function setWatchChannelLabel", js)
        self.assertIn("querySelector('.watch-meta-label')", js)
        self.assertIn("styles.css?v=hxylive", html)
        self.assertNotIn('id="followIcon"', html)
        self.assertNotIn('id="recordIcon"', html)
        self.assertIn("function updateWatchIdentity", js)
        self.assertIn("data.profileImageUrl || data.profile_image_url", js)
        self.assertIn("lastWatchProfileImageUrl", js)
        self.assertIn("applyPreferredLiveAudio", js)
        self.assertIn("return 1;", js)
        css = (ROOT / "static" / "styles.css").read_text()
        self.assertIn(".watch-channel-meta", css)
        self.assertIn("watch-meta-label", html)
        self.assertIn("watchChannelLabel", html)
        self.assertIn("watchProviderLabel", js)
        self.assertIn("watch-title-row", html)
        self.assertNotIn("URL:", html)
        self.assertIn("Chaturbate:", html)
        self.assertIn("Followers:", html)
        self.assertIn("Viewers:", html)
        self.assertNotIn("Status:", html)
        self.assertIn(".watch-title-row", css)
        self.assertIn("gap: 0.55rem;", css)
        self.assertIn(".watch-btn.record-btn.active", css)
        self.assertNotIn(".watch-recording-modal", css)

    def test_recordings_page_redirects_to_media(self):
        main = (ROOT / "app" / "main.py").read_text()

        self.assertIn('@app.get("/recordings")', main)
        self.assertIn('RedirectResponse(url="/media", status_code=307)', main)
        self.assertNotIn('return FileResponse(str(STATIC_DIR / "recordings.html"))', main)

    def test_discover_preserves_filter_state_in_url(self):
        js = (ROOT / "static" / "discover.js").read_text()
        html = (ROOT / "static" / "discover.html").read_text()
        css = (ROOT / "static" / "styles.css").read_text()

        self.assertIn("function readDiscoverStateFromUrl", js)
        self.assertIn("function syncDiscoverStateToUrl", js)
        self.assertIn("applyDiscoverStateToControls", js)
        self.assertIn("window.history.replaceState", js)
        self.assertIn("window.addEventListener('popstate'", js)
        self.assertIn("discover.js?v=hxylive-yt2", html)
        self.assertIn("styles.css?v=hxylive-ui52", html)
        self.assertIn("discover-avatar-placeholder", js)
        self.assertIn("img\\.doppiocdn\\.net\\/snapshot\\/", js)
        self.assertIn("static-proxy.strpst.com", js)
        self.assertIn("thumb\\.live\\.mmcdn\\.com\\/riw\\/", js)
        self.assertIn("fillMissingChaturbateAvatars", js)
        self.assertIn("/api/discover/profile-images", js)
        self.assertIn("cache: 'no-store'", js)
        self.assertIn("maybeRefetchStaleDiscoverRoster", js)
        self.assertIn("pageshow", js)
        self.assertNotIn("DISCOVER_ROSTER_REFRESH_MS", js)
        self.assertNotIn("discoverUsernameSet", js)
        # Thumbnail refresh must not overwrite the circular face with live cover.
        self.assertIn(".discover-card-thumb img", js)
        self.assertIn(".discover-identity .discover-avatar", js)
        self.assertNotIn("discover-card-info-head", js)
        self.assertNotIn("discover-card-btn-icon", js)
        self.assertIn("discover-card-actions", js)
        self.assertIn("discover-card-btn", js)
        self.assertIn("create-card-btn", js)
        self.assertIn(".discover-card-btn.create-card-btn", css)
        self.assertIn("font-size: 0.9rem !important;", css)
        self.assertIn("toggleRecordingOnCard", js)
        self.assertIn("openCreateCardDialog", js)
        self.assertIn("function openExternalLive", js)
        self.assertIn("opensExternalLive = cardSource === 'youtube'", js)
        self.assertIn("Discover must not route YouTube into the in-app live room", js)
        self.assertIn("function updateDiscoverRecordButton", js)
        self.assertIn("loadCardAndRecordingSets", js)
        self.assertIn("/api/media-profiles/ensure-card", js)
        self.assertIn("sourceType: source", js)
        self.assertIn("channelUsername: username", js)
        self.assertNotIn("toggleFollowOnCard", js)
        self.assertNotIn("openDiscoverRecordingModal", js)
        self.assertNotIn("recordingModal", html)
        self.assertNotIn("Set recording", js)
        self.assertNotIn("discover-follow-heart", js)
        self.assertIn("discover_categories.js?v=hxylive", html)
        self.assertIn('id="categoryFilters"', html)
        self.assertIn('id="tagInput"', html)
        self.assertIn('id="activeTagFilters"', html)
        self.assertIn("Filter by tag...", html)
        self.assertNotIn("(press Enter)", html)
        self.assertIn('class="discover-controls"', html)
        self.assertIn('class="tag-input-container"', html)
        self.assertNotIn('class="tag-filter-section"', html)
        self.assertIn("function addTagFilter", js)
        self.assertIn("function pickDiscoverDisplayTags", js)
        self.assertIn("discover-tag-active", js)
        self.assertIn("function handleTagInput", js)
        self.assertIn("discover-tags", js)
        self.assertIn("discover-tag", js)
        self.assertIn("DISCOVER_TAG_EMPTY_PAGE_ADVANCE_MAX", js)
        self.assertIn("setupInfiniteDiscoverScroll", js)
        self.assertIn("fetchDiscover({ append: true })", js)
        self.assertIn("refillSamePage", js)
        self.assertIn("DISCOVER_EMPTY_PAGE_RETRY_MAX", js)
        self.assertIn("emptyPageRetryCount", js)
        self.assertIn("data.supported === false", js)
        self.assertIn("Category not supported on this platform", js)
        self.assertIn("discoverHasMore = false", js)
        self.assertIn("loadedModelKeys = new Set()", js)
        self.assertIn("discover-loading-message", js)
        self.assertIn("dataset.mode", js)
        self.assertIn("Loading more...", js)
        # Empty+has_more must schedule same-page refill, not silently stop.
        self.assertIn("scheduleSamePageRefill", js)
        self.assertIn("fetchDiscover({ refillSamePage: true })", js)
        self.assertNotIn(
            "if (append && added === 0 && !(data.models || []).length) {\n          discoverHasMore = false;",
            js,
        )
        self.assertNotIn("updateDiscoverLoadStatus(append ? 'Loading more...' : 'Loading...')", js)
        self.assertNotIn('id="prevBtn"', html)
        self.assertNotIn('id="nextBtn"', html)
        self.assertIn("Create card", js)
        self.assertIn("Create and record", js)
        self.assertIn("function openCreateCardDialog", js)
        self.assertIn("function updateDiscoverRecordButton", js)
        self.assertNotIn("function updateDiscoverFollowButton", js)
        self.assertNotIn("(isFollowed ? 'Unfollow' : 'Follow')", js)
        self.assertNotIn("&#9829;", js)
        self.assertNotIn("&#9825;", js)

    def test_provider_settings_has_account_controls_for_sync_capable_providers(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("Import from Chrome", js)
        self.assertIn("function importProviderSessionFromChrome", js)
        self.assertNotIn("function loginProvider", js)
        self.assertNotIn("function reconnectProvider", js)
        self.assertNotIn("function importProviderSession(", js)
        self.assertNotIn("Paste cookies", js)
        self.assertNotIn("provider-session-import", js)
        self.assertNotIn("provider-login", js)
        self.assertIn("supportsAccount = caps.can_login === true", js)
        self.assertNotIn("var canPasswordLogin = caps.can_password_login === true", js)
        self.assertIn("Log into this site in Google Chrome on this Mac, then Import from Chrome. Use Sync follows afterwards to open Media reconcile.", js)
        self.assertIn("Use Sync follows to open Media and reconcile local cards with this site", js)
        self.assertIn("/media?reconcile=", js)
        self.assertNotIn("For pick-and-choose sync", js)
        self.assertNotIn("long-press the site filter", js)
        self.assertIn("/provider-cookies", js)
        self.assertIn("/api/mac/helper/import-session", js)
        self.assertIn("providerAccountControls(source, status, caps)", js)
        self.assertIn("function postProviderSession", js)
        self.assertIn("/api/providers?verify=1", js)
        self.assertIn("Checking provider sessions...", js)
        self.assertIn("Session Expired", js)
        self.assertIn("providerStatusSessionExpired", js)
        self.assertIn("hxylive-audit3", (ROOT / "static" / "settings.html").read_text())

    def test_recording_lifecycle_audit_ui_is_wired(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()
        main = (ROOT / "app" / "main.py").read_text()

        self.assertIn('data-tab="lifecycle"', html)
        self.assertIn('id="tab-lifecycle"', html)
        self.assertIn("Recording lifecycle", html)
        self.assertIn("auditSessionList", html)
        self.assertIn("Needs attention", js)
        self.assertIn("loadRecordingLifecycle", js)
        self.assertIn("/api/ops/recording-lifecycle", js)
        self.assertIn("/api/ops/recording-lifecycle", main)
        self.assertIn("list_lifecycle_sessions", main)
        # Lifecycle sits directly under Recording in the nav.
        rec = html.find('data-tab="recording"')
        life = html.find('data-tab="lifecycle"')
        proc = html.find('data-tab="processes"')
        self.assertTrue(0 <= rec < life < proc)

    def test_provider_settings_keeps_local_status_for_non_account_providers(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("supportsAccount ? providerStatusText(status) : 'Local'", js)
        self.assertIn("Live, recording and local follows", js)
        self.assertIn("Live, recording, remote sync and follow", js)
        self.assertIn("Credentials Saved", js)
        self.assertIn("Session Required", js)
        self.assertIn("Login Failed", js)
        self.assertIn("Saved credentials are stored", js)
        self.assertIn("Automatic login was blocked", js)
        self.assertIn("Browser session data is saved", js)
        self.assertIn("function providerStatusNeedsSessionImport", js)
        self.assertIn("function providerStatusLoginFailed", js)
        self.assertIn("var canSync = connected && caps.can_sync_following === true", js)
        self.assertNotIn("function providerConnectionProviders(providers)", js)
        self.assertIn("No providers configured.", js)
        self.assertNotIn("Paste a Cookie header only if Chrome import is unavailable", js)

    def test_provider_settings_lists_all_providers_with_capability_checks(self):
        js = (ROOT / "static" / "settings.js").read_text()
        css = (ROOT / "static" / "styles.css").read_text()
        html = (ROOT / "static" / "settings.html").read_text()

        self.assertIn("providers = providers || []", js)
        self.assertIn("function providerCapabilityChecks(caps)", js)
        self.assertIn("providerCapabilityCheck('Discover', !!caps.can_discover)", js)
        self.assertIn("providerCapabilityCheck('Record', !!caps.can_record)", js)
        self.assertIn("providerCapabilityCheck('Follow / Unfollow', !!caps.can_follow)", js)
        self.assertIn("providerCapabilityCheck('Sync', !!caps.can_sync_following)", js)
        self.assertIn("provider-capability-icon", js)
        self.assertIn("function providerEnabledControl", js)
        self.assertIn("function toggleProviderEnabled", js)
        self.assertIn("/api/providers/' + encodeURIComponent(source) + '/enabled", js)
        self.assertIn("provider-enabled-control", js)
        self.assertIn("&#10003;", js)
        self.assertIn("&#10005;", js)
        self.assertIn(".provider-capability-list", css)
        self.assertIn(".provider-capability-icon", css)
        self.assertIn(".provider-capability.is-enabled .provider-capability-icon", css)
        self.assertIn(".provider-capability.is-disabled .provider-capability-icon", css)
        self.assertIn(".provider-enabled-control", css)
        self.assertNotIn(".provider-capability:has(input:checked)", css)
        self.assertIn(".status-indicator.available", css)
        self.assertIn("<h3>Providers</h3>", html)

    def test_provider_settings_maps_login_error_codes(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertNotIn("Automatic Stripchat account login failed;", js)
        self.assertIn("Automatic account login failed. Check credentials", js)
        self.assertIn("function providerStatusError", js)
        self.assertIn("providerConnectionError", js)

    def test_provider_settings_does_not_expose_removed_subscription_sources(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertNotIn("function headerValue", js)
        self.assertNotIn("function onlyFansPayloadFromObject", js)
        self.assertNotIn("onlyfans", js.lower())
        self.assertNotIn("manyvids", js.lower())
        self.assertNotIn("fansly", js.lower())
        self.assertIn("userAgent:", js)
        self.assertIn("postProviderSession", js)


if __name__ == "__main__":
    unittest.main()
