import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class SettingsStaticTests(unittest.TestCase):
    def test_recording_filename_format_control_is_wired(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("filenameFormatSelect", html)
        self.assertIn("username_timestamp", html)
        self.assertIn("Recording Filename Format", html)
        self.assertIn("filenameFormatSelect", js)
        self.assertIn("data.filename_format || 'timestamp'", js)
        self.assertIn("updateRecordingSetting('filename_format', this.value)", html)

    def test_auto_record_uses_configured_interval_and_cooldown(self):
        main = (ROOT / "app" / "main.py").read_text()

        self.assertNotIn("await asyncio.sleep(180)", main)
        self.assertIn("check_interval = await get_check_interval_seconds(db)", main)
        self.assertIn("failure_cooldowns", main)

    def test_settings_header_status_badge_is_removed(self):
        html = (ROOT / "static" / "settings.html").read_text()

        self.assertNotIn("settings-page-kicker", html)
        self.assertNotIn("Settings status", html)
        self.assertNotIn("settingsApiPill", html)
        self.assertNotIn("settingsApiDot", html)

    def test_shared_header_does_not_show_gitops_button(self):
        header = (ROOT / "static" / "header.html").read_text()
        loader = (ROOT / "static" / "loader.js").read_text()

        self.assertNotIn("GitOps", header)
        self.assertNotIn("gitStatusBtn", header)
        self.assertNotIn("gitStatusIcon", header)
        self.assertNotIn("gitStatusText", header)
        self.assertNotIn("/api/git/status", loader)
        self.assertNotIn("checkGitStatus", loader)
        self.assertIn('id="logoutBtn"', header)
        self.assertIn("data.authentication_required", loader)
        self.assertIn("fetch('/api/logout', { method: 'POST' })", loader)

    def test_settings_application_tab_is_removed(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertNotIn('data-tab="application"', html)
        self.assertNotIn('id="tab-application"', html)
        self.assertNotIn('id="appVersionSetting"', html)
        self.assertNotIn('id="apiStatus"', html)
        self.assertNotIn("appVersionSetting", js)

    def test_flaresolverr_settings_url_can_be_edited(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("flareUrlInput", html)
        self.assertIn("flareSaveBtn", html)
        self.assertIn("saveFlareSolverrUrl", js)
        self.assertIn("loadFlareSolverrSettings", js)
        self.assertIn("/api/settings/flaresolverr", js)
        self.assertIn("FlareSolverr URL saved", js)
        self.assertNotIn("configured via environment variables", html)

    def test_flaresolverr_is_not_configured_by_environment_variables(self):
        files = [
            "app/main.py",
            "app/core/config.py",
            "app/providers/browser.py",
            "app/services/flaresolverr.py",
            "docker-compose.yml",
            "README.md",
        ]
        text = "\n".join((ROOT / path).read_text() for path in files)

        self.assertNotIn("FLARESOLVERR_URL", text)
        self.assertNotIn("HXYLIVE_FLARESOLVERR_URL", text)
        self.assertNotIn("FLARESOLVERR_MAX_TIMEOUT", text)
        self.assertNotIn("HXYLIVE_FLARESOLVERR_TIMEOUT_MS", text)
        self.assertNotRegex(text, r"os\.getenv\([^)]*FLARESOLVERR")

    def test_recording_settings_exposes_check_interval_control(self):
        html = (ROOT / "static" / "settings.html").read_text()
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn('id="checkIntervalInput"', html)
        self.assertIn("check_interval_seconds", html)
        self.assertIn("function normalizeCheckIntervalSeconds", js)
        self.assertIn("function setCheckIntervalInput", js)
        self.assertIn("data.check_interval_seconds", js)

    def test_blacklisted_tags_use_dom_events_instead_of_inline_javascript(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("removeButton.addEventListener('click'", js)
        self.assertIn("chip.appendChild(document.createTextNode(String(tag)))", js)
        self.assertNotIn("onclick=\"removeBlacklistedTag", js)

    def test_dynamic_inline_handlers_use_javascript_string_escaping(self):
        for filename in ("discover.js", "following.js", "settings.js"):
            js = (ROOT / "static" / filename).read_text()
            self.assertIn("function escapeInlineJs(value)", js, filename)
            self.assertIn(".replace(/'/g, '\\\\x27')", js, filename)
            self.assertIn(".replace(/</g, '\\\\x3c')", js, filename)

        discover = (ROOT / "static" / "discover.js").read_text()
        following = (ROOT / "static" / "following.js").read_text()
        settings = (ROOT / "static" / "settings.js").read_text()
        self.assertIn("toggleFollowOnCard(\\'' + escapeInlineJs(model.username)", discover)
        self.assertIn("unfollowFollowingModel(\\'' + escapeInlineJs(username)", following)
        self.assertIn("navigator.clipboard.writeText(\\'' + escapeInlineJs(input)", settings)

    def test_hls_player_dependency_is_version_pinned_with_integrity(self):
        expected_src = "https://cdn.jsdelivr.net/npm/hls.js@1.6.16/dist/hls.min.js"
        expected_integrity = (
            "sha384-5E8B0pTlZZJMabWpC0fyYf6OUpe15jJij34BqBAh4NXoHAlLNOjCPRrwtOXOQFAn"
        )
        html = (ROOT / "static" / "watch.html").read_text()
        self.assertIn(expected_src, html)
        self.assertIn(expected_integrity, html)
        self.assertIn('crossorigin="anonymous"', html)
        self.assertNotIn("hls.js@latest", html)

    def test_watch_quality_switches_server_renditions_for_single_level_hls(self):
        html = (ROOT / "static" / "watch.html").read_text()
        js = (ROOT / "static" / "watch.js").read_text()
        main = (ROOT / "app" / "main.py").read_text()

        self.assertIn('id="watchQualitySelect"', html)
        self.assertIn("serverQualityOptions = [1080, 720, 480]", js)
        self.assertIn("function watchQualityHeights()", js)
        self.assertIn("Auto (network ABR)", js)
        self.assertNotIn("return 'Source'", js)
        self.assertNotIn("return 'Source '", js)
        self.assertNotIn(">Source</option>", js)
        self.assertNotIn("Source ' + ordinal", js)
        self.assertIn("query.quality = Number(quality)", js)
        self.assertIn("server:' + height", js)
        self.assertIn("startStreamWithUrl(data.streamUrl, data.streamType, true)", js)
        self.assertIn("quality: Optional[int] = None", main)
        self.assertIn('"qualityOptions": [1080, 720, 480]', main)
        self.assertIn("max_height = quality", main)

    def test_watch_pause_does_not_auto_resume_on_hls_level_reload(self):
        js = (ROOT / "static" / "watch.js").read_text()
        self.assertIn("let userPausedLive = false", js)
        self.assertIn("function pauseLivePlayback()", js)
        self.assertIn("if (!video || userPausedLive) return", js)
        self.assertNotIn("if (video.paused) startMutedAutoplay(video)", js)

    def test_tests_center_covers_local_diagnostics(self):
        js = (ROOT / "static" / "settings.js").read_text()
        test_ids = set(re.findall(r"id: '([^']+)'", js))

        self.assertTrue(
            {
                "api",
                "routes",
                "providers",
                "system",
                "recording",
                "following",
                "processes",
                "flaresolverr",
                "recordings",
                "media-imports",
                "blacklist",
            }.issubset(test_ids)
        )
        self.assertNotIn("chaturbate", test_ids)
        self.assertNotIn("cam4", test_ids)
        self.assertNotRegex(js, r"id:\s*'chaturbate'")
        self.assertNotRegex(js, r"id:\s*'cam4'")
        self.assertNotRegex(js, r"name:\s*'Chaturbate account'")
        self.assertNotRegex(js, r"name:\s*'CAM4 account'")
        self.assertIn("Legacy dashboard route still exists", js)
        self.assertIn("Removed provider still registered", js)
        self.assertIn("Missing status for", js)
        self.assertIn("All four providers should expose account login", js)
        self.assertIn("All four providers should expose remote sync", js)

    def test_following_page_lists_local_follow_providers(self):
        js = (ROOT / "static" / "following.js").read_text()

        self.assertIn("function providersForFollowing(models)", js)
        self.assertIn("providerBySource[sourceType] = Object.assign({}, provider", js)
        self.assertNotIn("if (caps.can_sync_following === true) {\n      providerBySource[sourceType]", js)
        self.assertIn("No local follows saved for this provider.", js)

    def test_media_page_has_profile_filter_and_continuous_playback(self):
        html = (ROOT / "static" / "media.html").read_text()
        header = (ROOT / "static" / "header.html").read_text()
        js = (ROOT / "static" / "media.js").read_text()
        css = (ROOT / "static" / "styles.css").read_text()

        self.assertNotIn('href="/recordings"', header)
        self.assertNotIn('data-page="recordings"', header)
        self.assertNotIn("Recordings</a>", header)
        self.assertIn('href="/media" class="nav-link" data-page="media">Media</a>', header)
        self.assertNotIn('href="/stash"', header)
        self.assertIn("<title>Media - HXYLIVE</title>", html)
        self.assertNotIn("mediaNewProfileBtn", html)
        self.assertNotIn("mediaProfileFilter", html)
        self.assertNotIn("mediaAutoRecordFilter", html)
        self.assertNotIn("mediaProfilePrev", html)
        self.assertNotIn("mediaProfileNext", html)
        self.assertNotIn("mediaProfileDetail", html)
        self.assertNotIn("mediaProfileFilterBtn", html)
        self.assertNotIn("mediaProfileClearBtn", html)
        self.assertNotIn("mediaUploadBtn", html)
        self.assertNotIn("mediaUploadForm", html)
        self.assertNotIn("/uploads", html)
        self.assertIn("Date of birth", html)
        self.assertIn("Profile image URL", html)
        self.assertIn("Babepedia page URL", html)
        self.assertIn("Fetch Babepedia image", html)
        self.assertIn("profileSourcesList", html)
        self.assertIn("profileAddSourceBtn", html)
        self.assertIn("Add source", html)
        self.assertNotIn("mediaUnwatchedOnlyToggle", html)
        self.assertNotIn(">Unwatched<", html)
        self.assertIn("profileImageUrl", js)
        self.assertIn("streamSources", js)
        self.assertIn("channelUsername", js)
        self.assertIn("channelUsernameFromUrl", js)
        self.assertIn("sourceTypeFromUrl", js)
        self.assertIn("{ value: 'twitch', label: 'Twitch'", js)
        self.assertIn("{ value: 'chaturbate', label: 'Chaturbate'", js)
        self.assertIn("selectedProfile", js)
        self.assertIn("filterProfile", js)
        self.assertIn("formatProfileMediaCounts", js)
        self.assertNotIn("mediaProfileFilter", js)
        self.assertNotIn("autoRecordFilter", js)
        self.assertIn("profileSearch", js)
        self.assertIn("function visibleProfiles()", js)
        self.assertIn("No profiles match this filter", js)
        self.assertIn("media-profile-menu-btn", js)
        self.assertIn('data-profile-action="settings"', js)
        self.assertNotIn("renderProfileDetail", js)
        self.assertNotIn("filterSelectedProfile", js)
        self.assertNotIn("clearSelectedProfile", js)
        self.assertIn("showNextPrompt", js)
        self.assertIn("nextVideoItem", js)
        self.assertIn("data-next-action", js)
        self.assertIn("setupMediaProfileVolume", js)
        self.assertIn("video_volume_' + username", js)
        self.assertIn("/api/models/' + encodeURIComponent(username) + '/volume", js)
        self.assertIn("window.addEventListener('beforeunload', flushMediaProfileVolume)", js)
        self.assertNotIn("openUploadModal", js)
        self.assertNotIn("uploadMediaFiles", js)
        self.assertNotIn("/uploads", js)
        self.assertNotIn("<label>Channel<input", js)
        self.assertNotIn('data-source-field="channelUsername" type="text"', js)
        self.assertNotIn("profile.thumbnail", js)
        self.assertNotIn("unwatchedOnly", js)
        self.assertNotIn("params.set('watched', 'unwatched')", js)
        self.assertNotIn('media-tag watched', js)
        self.assertIn("params.set('metadata', 'lazy')", js)
        self.assertIn("formatDurationClock", js)
        self.assertIn("value.getFullYear()", js)
        self.assertIn("item.resolution", js)
        self.assertIn("matching videos", js)
        self.assertIn("media-heading-count", js)
        self.assertNotIn("All devices", js)
        self.assertNotIn("media-heading-filters", js)
        self.assertIn("mediaSelectAllBtn", html)
        self.assertIn("mediaInvertSelectionBtn", html)
        self.assertIn("selectAllVisibleVideos", js)
        self.assertIn("invertVisibleVideoSelection", js)
        self.assertIn('class="media-card-profile-id"', js)
        self.assertIn('data-media-action="profile"', js)
        self.assertIn("profileIdLabel", js)
        self.assertIn("profileLabel(profileForItem)", js)
        self.assertIn("selectProfile(profileLink.dataset.profile || '', true)", js)
        self.assertIn('data-profile-action="record"', js)
        self.assertIn("/api/media-profiles/' + encodeURIComponent(username) + '/auto-record", js)
        self.assertIn("Recording enabled for ", js)
        self.assertIn("Watch live", js)
        self.assertIn("preferOnline", js)
        self.assertIn("ev.metaKey || ev.ctrlKey", js)
        self.assertIn("Online playback needs a VPS copy of this video", js)
        self.assertIn("⌘/Ctrl-click to play online", js)
        self.assertNotIn("&#9679;", js)
        self.assertNotIn("&#9675;", js)
        self.assertLess(
            js.index('data-profile-action="follow"'),
            js.index('data-profile-action="record"'),
        )
        self.assertLess(
            js.index('data-profile-action="record"'),
            js.index('data-profile-action="watch"'),
        )
        self.assertLess(
            js.index('data-profile-action="watch"'),
            js.index('data-profile-action="settings"'),
        )
        self.assertIn("profile.autoRecord = !!data.autoRecord", js)
        self.assertIn("profile.streamSources = data.profile.streamSources", js)
        self.assertNotIn("Object.assign(profile, data.profile)", js)
        self.assertIn("mediaStorage", html)
        self.assertIn("mediaStorageRefreshBtn", html)
        self.assertIn("mediaProfileRefreshBtn", html)
        self.assertIn("VPS storage", html)
        self.assertNotIn("VPS storage health", html)
        self.assertNotIn("mediaStorageHealth", html)
        self.assertNotIn("Storage looks healthy", html)
        self.assertIn("Recording folder", html)
        self.assertIn("Processing / temporary", html)
        self.assertIn("Untracked / other", html)
        self.assertIn("Disk used", html)
        self.assertIn("Disk free", html)
        self.assertIn("mediaDiskUsedPercent", html)
        self.assertIn("mediaDiskFreePercent", html)
        self.assertNotIn('id="mediaVideoCount"', html)
        self.assertNotIn('id="mediaTotalSize"', html)
        self.assertNotIn("Videos:", html)
        self.assertNotIn('class="media-stats"', html)
        self.assertIn("media.js?v=hxylive-mac5", html)
        self.assertIn("formatLastLive", js)
        self.assertIn("media-profile-last-live", js)
        self.assertIn("lastLiveAt", js)
        self.assertIn("file.resolution", js)
        self.assertIn("styles.css?v=hxylive", html)
        self.assertIn("applyMediaVideoBoxSize", js)
        self.assertIn("parseMediaResolution", js)
        self.assertIn("object-position: center center", css)
        self.assertIn("{ value: 'locked', label: 'Locked' }", js)
        self.assertIn("function profileStatusDetail", js)
        self.assertIn(".media-profile-live-meta .locked", css)
        self.assertIn(".media-batch-actions .media-action-btn", (ROOT / "static" / "styles.css").read_text())
        self.assertIn("media-card-title-row", js)
        self.assertIn(".media-card-title-row", css)
        self.assertIn("showQuality", js)
        self.assertIn("refreshProfiles", js)
        self.assertIn("live_refresh", js)
        self.assertIn("scanMacAndRefresh(true, true)", js)
        self.assertIn("media-refresh-btn", html)
        self.assertIn(".media-refresh-btn", css)
        self.assertIn("mediaDeviceFilters", html)
        self.assertIn('data-device="all"', html)
        self.assertIn('data-device="vps"', html)
        self.assertIn('data-device="mac"', html)
        self.assertIn('data-device="both"', html)
        self.assertIn('class="media-device-btn active" data-device="all"', html)
        self.assertIn("deviceFilter: 'all'", js)
        self.assertIn("itemIsBoth", js)
        self.assertIn("media-filter-sep", html)
        self.assertIn(".media-filter-sep", css)
        self.assertIn("color: #a5b4fc !important", css)
        self.assertNotIn("mediaUnsyncedOnlyToggle", html)
        self.assertIn("buildUnifiedCatalog", js)
        self.assertIn("setDeviceFilter", js)
        self.assertIn("openLocally", js)
        self.assertIn("itemIsSelectable", js)
        self.assertIn("deleteSelectedMacCopies", js)
        self.assertIn("classifyDeleteItems", js)
        self.assertIn("buildDeletePlan", js)
        self.assertIn("mediaDeleteBothBody", html)
        self.assertIn("pendingBothChoices", js)
        self.assertIn("macThumbUrl", js)
        self.assertIn("locationLabel", js)
        self.assertIn("displayMediaTitle", js)
        self.assertIn("displayMediaIdTitle", js)
        self.assertIn("formatDateTimeSeconds", js)
        self.assertIn(":not(.media-refresh-btn)", css)
        self.assertIn(".media-refresh-btn", css)
        self.assertIn("background: var(--accent) !important", css)
        self.assertIn("reveal-local", js)
        self.assertIn("helperPostOrQueue('/open'", js)
        self.assertIn("helperPostOrQueue('/delete'", js)
        self.assertIn("/api/mac/helper/open", js)
        self.assertIn("/api/mac/helper/delete", js)
        self.assertIn("helperPostOrQueue", js)
        self.assertIn("MAC_HELPER_BASE + '/thumb?'", js)
        self.assertIn("watchFiledDownloads", js)
        self.assertIn("refreshMacListAfterFile", js)
        self.assertIn("MAC_HELPER_BASE + '/wait-filed'", js)
        self.assertIn("fetchVpsMacSnapshot", js)
        self.assertIn("applyMacSnapshot", js)
        self.assertIn("/api/mac/helper/snapshot", js)
        self.assertIn("macHelperDirect", js)
        self.assertIn(".media-device-filters", css)
        self.assertIn(".media-mac-path", css)
        self.assertIn("background: transparent !important", css)
        self.assertNotIn("mediaDeleteMacOnly", html)
        self.assertNotIn("mediaDeleteVpsOnly", html)
        self.assertNotIn("Delete Mac only", html)
        self.assertNotIn("Delete VPS only", html)
        self.assertIn(".media-delete-both-table", css)
        self.assertIn(".media-loc-tag", css)
        self.assertIn("media-profile-website-filters", html)
        self.assertIn(".media-profile-website-filters", css)
        self.assertIn("media-profile-channel-line", js)
        self.assertIn("providerLabel(sourceType)", js)
        self.assertIn("isLiveCoverAvatarUrl", js)
        self.assertIn("thumb\\.live\\.mmcdn\\.com\\/riw\\/", js)
        self.assertIn('referrerpolicy="no-referrer"', js)
        self.assertIn(".media-profile-channel-line", css)
        self.assertIn("data.storage", js)
        self.assertIn("recordingFolderFormatted", js)
        self.assertIn("diskFreePercent", js)
        self.assertIn("mediaStorageRefreshBtn", js)
        self.assertIn("mediaProfileRefreshBtn", js)
        self.assertIn('id="mediaProfileRefreshBtn"', html)
        self.assertIn('id="mediaStorageRefreshBtn"', html)
        self.assertIn('class="media-profile-source-btn media-refresh-btn" id="mediaProfileRefreshBtn"', html)
        self.assertIn('class="media-profile-source-btn media-refresh-btn" id="mediaStorageRefreshBtn"', html)
        self.assertNotIn("$('mediaVideoCount')", js)
        self.assertNotIn("$('mediaTotalSize')", js)
        self.assertIn(".media-storage-grid", css)
        self.assertNotIn(".media-storage-refresh-btn", css)
        self.assertNotIn("Every recording in this filter", js)
        self.assertNotIn("media-open-local-btn", js)
        self.assertNotIn(">Open locally<", js)
        self.assertIn("return 'BOTH'", js)
        self.assertIn("return 'MAC'", js)
        self.assertIn("return 'VPS'", js)
        self.assertIn(".media-storage-metric-row", css)
        self.assertIn("grid-template-columns: 1fr;", css)
        self.assertIn(".media-profile-record-btn:not(.is-enabled)", css)
        self.assertIn("var(--accent)", css)
        self.assertNotIn("media-profile-handle", js)
        self.assertNotIn("var showHandle =", js)
        self.assertIn('data-profile-action="follow"', js)
        self.assertIn("toggleProfileFollow", js)
        self.assertNotIn("discover-follow-heart", js)
        self.assertIn("media-profile-follow-btn", js)
        self.assertIn("profile.isFollowing ? 'Unfollow' : 'Follow'", js)
        self.assertIn("formatLastLive", js)
        self.assertIn("formatLastSeen", js)
        self.assertIn("media-profile-last-live", js)
        self.assertIn("lastLiveAt", js)
        self.assertIn("lastSeenOnlineAt", js)
        self.assertIn(".media-profile-actions .media-profile-follow-btn", css)
        self.assertIn(".media-profile-actions .media-profile-record-btn", css)
        self.assertIn(".media-profile-actions .media-profile-watch-btn", css)
        self.assertIn(".media-profile-actions .media-profile-menu-btn", css)
        self.assertIn("flex-direction: column", css)
        self.assertIn("align-items: stretch", css)
        self.assertIn("renderAllProfilesCard", js)
        self.assertIn("media-all-profiles-card", js)
        self.assertIn('data-all-profiles="1"', js)
        self.assertIn("All streamers", js)
        self.assertIn("mediaProfileSourceFilters", html)
        self.assertIn("mediaProfileStatusFilters", html)
        self.assertIn("filterSource", js)
        self.assertIn("filterLiveStatus", js)
        self.assertIn("setProfileSourceFilter", js)
        self.assertIn("setProfileLiveStatusFilter", js)
        self.assertIn("PROFILE_LIVE_STATUS_OPTIONS", js)
        self.assertIn("PROFILE_GLOBAL_LIVE_STATUS_OPTIONS", js)
        self.assertIn("setGlobalLiveStatusFilter", js)
        self.assertIn('data-source="all"', js)
        self.assertIn('data-live-status=', js)
        self.assertIn("data-global-live-status=", js)
        self.assertIn('row.hidden = true', js)
        self.assertIn(".media-profile-website-row", css)
        self.assertIn(".media-profile-status-row", css)
        self.assertIn(".media-profile-website-sep", css)
        self.assertIn(".media-profile-source-btn", css)
        self.assertIn(".media-profile-status-btn", css)
        self.assertIn("All videos", js)
        self.assertIn("mediaProfilePagination", html)
        self.assertIn("mediaProfilePageNumbers", html)
        self.assertIn("PROFILE_PAGE_ROWS = 2", js)
        self.assertIn("setProfilePage", js)
        self.assertIn("renderProfilePagination", js)
        self.assertIn("data-profile-page", js)
        self.assertIn(".media-profile-pagination", css)
        self.assertIn("color: #a5b4fc !important", css)
        self.assertIn(".media-card-profile-id", css)
        self.assertIn("mediaSortButtons", html)
        self.assertNotIn("mediaSortSelect", html)
        self.assertIn("isWatched", js)
        self.assertNotIn("mediaUnwatchedOnlyToggle", html)
        self.assertIn(".media-next-prompt", css)
        self.assertIn(".media-profile-menu-btn", css)
        self.assertIn(".media-profile-record-btn.is-enabled", css)
        self.assertIn("border-color: var(--accent) !important;", css)
        self.assertIn(".media-profile-actions", css)
        self.assertIn("min-height: 152px;", css)
        self.assertIn("grid-template-columns: repeat(3, minmax(0, 1fr));", css)
        self.assertIn("grid-template-columns: 82px minmax(0, 1fr) 118px;", css)
        self.assertIn("overflow: hidden;", css)
        self.assertIn("renderSourceFilters({});", (ROOT / "static" / "discover.js").read_text())
        self.assertIn("if (!hasCards) {", (ROOT / "static" / "discover.js").read_text())
        self.assertNotIn(".media-profile-detail", css)
        self.assertNotIn(".media-upload-modal", css)
        self.assertNotIn("M&eacute;dia", header)
        self.assertNotIn("Non vues", html)
        self.assertNotIn("Videos non vues", js)
        self.assertNotIn("Deja vu", js)

    def test_watch_page_uses_set_recording_profile_flow(self):
        html = (ROOT / "static" / "watch.html").read_text()
        js = (ROOT / "static" / "watch.js").read_text()

        self.assertIn("Set recording", html)
        self.assertIn("recordingModal", html)
        self.assertIn("recordingProfileSearch", html)
        self.assertIn("Existing profile", html)
        self.assertIn("New profile", html)
        self.assertIn("/api/media-profiles/link-live", js)
        self.assertIn("openRecordingModal", js)
        self.assertIn("submitCreateRecordingProfile", js)
        self.assertNotIn("Auto-Record", html)
        self.assertNotIn("Auto-Record", js)
        self.assertNotIn("toggleAutoRecord", js)
        self.assertIn('id="watchAvatar"', html)
        self.assertIn("watch-avatar-placeholder", html)
        self.assertIn("watch.js?v=hxylive", html)
        self.assertIn("function setWatchChannelLabel", js)
        self.assertIn("querySelector('.watch-meta-label')", js)
        self.assertIn("styles.css?v=hxylive", html)
        self.assertNotIn('id="followIcon"', html)
        self.assertNotIn('id="recordIcon"', html)
        self.assertIn("function updateWatchIdentity", js)
        self.assertIn("data.profileImageUrl || data.profile_image_url", js)
        self.assertIn("lastWatchProfileImageUrl", js)
        self.assertIn("applyPreferredLiveAudio", js)
        self.assertIn("return 1;", js)
        css = (ROOT / "static" / "styles.css").read_text()
        self.assertIn(".watch-channel-meta", css)
        self.assertIn("watch-meta-label", html)
        self.assertIn("watchChannelLabel", html)
        self.assertIn("watchProviderLabel", js)
        self.assertIn("watch-title-row", html)
        self.assertNotIn("URL:", html)
        self.assertIn("Chaturbate:", html)
        self.assertIn("Followers:", html)
        self.assertIn("Viewers:", html)
        self.assertNotIn("Status:", html)
        self.assertIn(".watch-title-row", css)
        self.assertIn("gap: 0.55rem;", css)

    def test_recordings_page_redirects_to_media(self):
        main = (ROOT / "app" / "main.py").read_text()

        self.assertIn('@app.get("/recordings")', main)
        self.assertIn('RedirectResponse(url="/media", status_code=307)', main)
        self.assertNotIn('return FileResponse(str(STATIC_DIR / "recordings.html"))', main)

    def test_discover_preserves_filter_state_in_url(self):
        js = (ROOT / "static" / "discover.js").read_text()
        html = (ROOT / "static" / "discover.html").read_text()

        self.assertIn("function readDiscoverStateFromUrl", js)
        self.assertIn("function syncDiscoverStateToUrl", js)
        self.assertIn("applyDiscoverStateToControls", js)
        self.assertIn("window.history.replaceState", js)
        self.assertIn("window.addEventListener('popstate'", js)
        self.assertIn("discover.js?v=hxylive", html)
        self.assertIn("styles.css?v=hxylive", html)
        self.assertIn("discover-avatar-placeholder", js)
        self.assertIn("img\\.doppiocdn\\.net\\/snapshot\\/", js)
        self.assertIn("static-proxy.strpst.com", js)
        self.assertIn("thumb\\.live\\.mmcdn\\.com\\/riw\\/", js)
        self.assertIn("fillMissingChaturbateAvatars", js)
        self.assertIn("/api/discover/profile-images", js)
        # Thumbnail refresh must not overwrite the circular face with live cover.
        self.assertIn(".discover-card-thumb img", js)
        self.assertIn(".discover-identity .discover-avatar", js)
        self.assertNotIn("discover-card-info-head", js)
        self.assertNotIn("discover-card-btn-icon", js)
        self.assertIn("discover-card-actions", js)
        self.assertIn("discover-card-btn", js)
        self.assertIn("openDiscoverRecordingModal", js)
        self.assertIn("recordingModal", html)
        self.assertNotIn("discover-follow-heart", js)
        self.assertIn("discover_categories.js?v=hxylive", html)
        self.assertIn('id="categoryFilters"', html)
        self.assertIn('id="tagInput"', html)
        self.assertIn('id="activeTagFilters"', html)
        self.assertIn("Filter by tag...", html)
        self.assertNotIn("(press Enter)", html)
        self.assertIn('class="discover-controls"', html)
        self.assertIn('class="tag-input-container"', html)
        self.assertNotIn('class="tag-filter-section"', html)
        self.assertIn("function addTagFilter", js)
        self.assertIn("function pickDiscoverDisplayTags", js)
        self.assertIn("discover-tag-active", js)
        self.assertIn("function handleTagInput", js)
        self.assertIn("discover-tags", js)
        self.assertIn("discover-tag", js)
        self.assertIn("DISCOVER_TAG_EMPTY_PAGE_ADVANCE_MAX", js)
        self.assertIn("setupInfiniteDiscoverScroll", js)
        self.assertIn("fetchDiscover({ append: true })", js)
        self.assertIn("refillSamePage", js)
        self.assertIn("DISCOVER_EMPTY_PAGE_RETRY_MAX", js)
        self.assertIn("emptyPageRetryCount", js)
        self.assertIn("data.supported === false", js)
        self.assertIn("Category not supported on this platform", js)
        self.assertIn("discoverHasMore = false", js)
        self.assertIn("loadedModelKeys = new Set()", js)
        self.assertIn("discover-loading-message", js)
        self.assertIn("dataset.mode", js)
        self.assertIn("Loading more...", js)
        # Empty+has_more must schedule same-page refill, not silently stop.
        self.assertIn("scheduleSamePageRefill", js)
        self.assertIn("fetchDiscover({ refillSamePage: true })", js)
        self.assertNotIn(
            "if (append && added === 0 && !(data.models || []).length) {\n          discoverHasMore = false;",
            js,
        )
        self.assertNotIn("updateDiscoverLoadStatus(append ? 'Loading more...' : 'Loading...')", js)
        self.assertNotIn('id="prevBtn"', html)
        self.assertNotIn('id="nextBtn"', html)
        self.assertIn("(isFollowed ? 'Unfollow' : 'Follow')", js)
        self.assertIn("function updateDiscoverFollowButton", js)
        self.assertIn("function updateDiscoverRecordButton", js)
        self.assertIn("btn.textContent = isFollowed ? 'Unfollow' : 'Follow'", js)
        self.assertNotIn("&#9829;", js)
        self.assertNotIn("&#9825;", js)

    def test_provider_settings_has_account_controls_for_sync_capable_providers(self):
        js = (ROOT / "static" / "settings.js").read_text()
        css = (ROOT / "static" / "styles.css").read_text()

        self.assertIn("Import Session", js)
        self.assertIn("function importProviderSession", js)
        self.assertIn("loginProvider", js)
        self.assertIn("reconnectProvider", js)
        self.assertIn("provider-session-import", js)
        self.assertIn("provider-login", js)
        self.assertIn("supportsAccount = caps.can_login === true", js)
        self.assertIn("var canPasswordLogin = caps.can_password_login === true", js)
        self.assertIn("Import a browser session to connect this account and sync follows", js)
        self.assertIn("providerAccountControls(source, status, caps)", js)
        self.assertIn("data.trusted === false", js)
        self.assertIn("data.skippedReason || data.message || 'Following sync skipped'", js)
        self.assertIn(".provider-session-import", css)
        self.assertIn(".provider-login", css)

    def test_provider_settings_keeps_local_status_for_non_account_providers(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertIn("supportsAccount ? providerStatusText(status) : 'Local'", js)
        self.assertIn("Live, recording and local follows", js)
        self.assertIn("Live, recording, remote sync and follow", js)
        self.assertIn("Credentials Saved", js)
        self.assertIn("Session Required", js)
        self.assertIn("Login Failed", js)
        self.assertIn("Saved credentials are stored", js)
        self.assertIn("automatic login was blocked", js)
        self.assertIn("Browser session data is saved", js)
        self.assertIn("function providerStatusNeedsSessionImport", js)
        self.assertIn("function providerStatusLoginFailed", js)
        self.assertIn("var canSync = connected && caps.can_sync_following === true", js)
        self.assertNotIn("function providerConnectionProviders(providers)", js)
        self.assertIn("No providers configured.", js)
        self.assertIn("Import a verified browser session", js)

    def test_provider_settings_lists_all_providers_with_capability_checks(self):
        js = (ROOT / "static" / "settings.js").read_text()
        css = (ROOT / "static" / "styles.css").read_text()
        html = (ROOT / "static" / "settings.html").read_text()

        self.assertIn("providers = providers || []", js)
        self.assertIn("function providerCapabilityChecks(caps)", js)
        self.assertIn("providerCapabilityCheck('Discover', !!caps.can_discover)", js)
        self.assertIn("providerCapabilityCheck('Record', !!caps.can_record)", js)
        self.assertIn("providerCapabilityCheck('Follow / Unfollow', !!caps.can_follow)", js)
        self.assertIn("providerCapabilityCheck('Sync', !!caps.can_sync_following)", js)
        self.assertIn("provider-capability-icon", js)
        self.assertIn("function providerEnabledControl", js)
        self.assertIn("function toggleProviderEnabled", js)
        self.assertIn("/api/providers/' + encodeURIComponent(source) + '/enabled", js)
        self.assertIn("provider-enabled-control", js)
        self.assertIn("&#10003;", js)
        self.assertIn("&#10005;", js)
        self.assertIn(".provider-capability-list", css)
        self.assertIn(".provider-capability-icon", css)
        self.assertIn(".provider-capability.is-enabled .provider-capability-icon", css)
        self.assertIn(".provider-capability.is-disabled .provider-capability-icon", css)
        self.assertIn(".provider-enabled-control", css)
        self.assertNotIn(".provider-capability:has(input:checked)", css)
        self.assertIn(".status-indicator.available", css)
        self.assertIn("<h3>Providers</h3>", html)

    def test_provider_settings_maps_login_error_codes(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertNotIn("Automatic Stripchat account login failed;", js)
        self.assertIn("Automatic account login failed. Check credentials", js)
        self.assertIn("function providerStatusError", js)
        self.assertIn("providerConnectionError", js)

    def test_provider_settings_does_not_expose_removed_subscription_sources(self):
        js = (ROOT / "static" / "settings.js").read_text()

        self.assertNotIn("function headerValue", js)
        self.assertNotIn("function onlyFansPayloadFromObject", js)
        self.assertNotIn("onlyfans", js.lower())
        self.assertNotIn("manyvids", js.lower())
        self.assertNotIn("fansly", js.lower())
        self.assertIn("userAgent:", js)
        self.assertIn("providerSessionPayload", js)


if __name__ == "__main__":
    unittest.main()
